version: "3"
services:
  backend:
    build:
      context: ./
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=backend-system
      - DB_PORT=3308
      - DB_USERNAME=root
      - DB_PASSWORD=Aman@1504
      - DB_NAME=backend-system
    networks:
      - app-network
networks:
  app-network:
    driver: bridge